apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scperturb-cmap.fullname" . }}-secrets
  labels:
    {{- include "scperturb-cmap.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "scperturb-cmap.databaseUrl" . | quote }}
